spring.application.name=server-sentinel

spring.task.scheduling.pool.size=1

discord.webhook.url=${DISCORD_WEBHOOK_URL:}
# cách khai báo các app cần được tự động khởi động lại nếu crash
# ALLOWED_AUTO_HEAL_CONTAINERS=app-bi-sap1,app-bi-sap2
sentinel.auto-heal.allowed=${ALLOWED_AUTO_HEAL_CONTAINERS:}